version: '3.8'
services:
  dockerapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: dockerapi:latest
    ports:
      - "8080:5000"     # HTTP (container: 8080 -> host: 5000)
      - "8081:5001"     # HTTPS (container: 8081 -> host: 5001)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=p@ssw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./src/DockerAPI/certs:/https:ro  # Map the certs folder into the container
