name: CI

on:
  push:
    branches: [ main, dev, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/DockerAPI/DockerAPI.csproj

      - name: Build
        run: dotnet build --no-restore ./src/DockerAPI/DockerAPI.csproj

      - name: Test
        run: dotnet test --no-build --verbosity normal ./src/DockerAPI/DockerAPI.csproj

      - name: Build Docker image
        run: docker build -f Dockerfile -t dotnetapi-docker .
